export type Categoria = {
  slug: string
  nome: string
  cor: string // classe de cor de fundo do badge/realce
  ilustracao: string
}

export type Atividade = {
  slug: string
  numero: number
  titulo: string
  categoriaSlug: string
  objetivo: string
  materiais: string[]
  comoPreparar: string[]
  comoAplicar: string[]
  variacao: string
  // Cartões de figuras (palavra + ícone lucide), renderizados em HTML
  cartoes?: { palavra: string; icone: string }[]
}

export const categorias: Categoria[] = [
  {
    slug: "linguagem-oral",
    nome: "Linguagem oral",
    cor: "bg-brand-blue",
    ilustracao: "/kit/cat-linguagem.png",
  },
  {
    slug: "vocabulario-categorias",
    nome: "Vocabulário e categorias",
    cor: "bg-brand-green",
    ilustracao: "/kit/cat-vocabulario.png",
  },
  {
    slug: "fala-articulacao",
    nome: "Fala e articulação",
    cor: "bg-orange-500",
    ilustracao: "/kit/cat-fala.png",
  },
  {
    slug: "consciencia-fonologica",
    nome: "Consciência fonológica",
    cor: "bg-sky-500",
    ilustracao: "/kit/cat-consciencia.png",
  },
  {
    slug: "atencao-memoria",
    nome: "Atenção e memória auditiva",
    cor: "bg-amber-500",
    ilustracao: "/kit/cat-memoria.png",
  },
  {
    slug: "sequencia-narrativa",
    nome: "Sequência lógica e narrativa",
    cor: "bg-brand-pink",
    ilustracao: "/kit/cat-sequencia.png",
  },
]

export const atividades: Atividade[] = [
  // ---------------- Linguagem oral ----------------
  {
    slug: "monte-uma-frase",
    numero: 1,
    titulo: "Monte uma Frase",
    categoriaSlug: "linguagem-oral",
    objetivo: "Estimular a organização de frases simples com apoio visual, ampliando a estrutura da linguagem oral.",
    materiais: ["Cartões de personagens", "Cartões de ações", "Cartões de objetos ou lugares"],
    comoPreparar: [
      "Imprima e recorte os cartões das três colunas abaixo.",
      "Organize os cartões em três grupos: quem, o que faz e onde/o quê.",
    ],
    comoAplicar: [
      "Peça para a criança escolher um cartão de cada grupo.",
      "Ajude-a a juntar os cartões formando uma frase, por exemplo: 'O menino chuta a bola'.",
      "Peça para ela repetir a frase completa apontando para cada cartão.",
      "Comemore cada frase montada e incentive variações.",
    ],
    variacao: "Para crianças com mais repertório, peça frases maiores acrescentando 'quando' ou 'por quê'.",
    cartoes: [
      { palavra: "Menino", icone: "User" },
      { palavra: "Menina", icone: "User" },
      { palavra: "Cachorro", icone: "Dog" },
      { palavra: "Chutar", icone: "Footprints" },
      { palavra: "Comer", icone: "Utensils" },
      { palavra: "Pular", icone: "Rabbit" },
      { palavra: "Bola", icone: "CircleDot" },
      { palavra: "Casa", icone: "House" },
      { palavra: "Parque", icone: "Trees" },
    ],
  },
  {
    slug: "o-que-esta-acontecendo",
    numero: 2,
    titulo: "O que Está Acontecendo?",
    categoriaSlug: "linguagem-oral",
    objetivo: "Desenvolver o discurso descritivo, levando a criança a falar sobre cenas do dia a dia.",
    materiais: ["Cartões de cenas do cotidiano", "Lista de perguntas de apoio"],
    comoPreparar: [
      "Imprima os cartões de cenas e deixe-os virados para baixo.",
      "Tenha em mãos as perguntas de apoio (quem, onde, o que está fazendo).",
    ],
    comoAplicar: [
      "A criança vira um cartão e observa a cena por alguns segundos.",
      "Faça perguntas abertas: 'O que está acontecendo aqui?'.",
      "Estimule a criança a descrever pessoas, ações e lugares.",
      "Amplie a resposta dela acrescentando um detalhe novo.",
    ],
    variacao: "Peça para a criança inventar o que aconteceu antes e o que vai acontecer depois da cena.",
    cartoes: [
      { palavra: "Tomar banho", icone: "Bath" },
      { palavra: "Brincar", icone: "ToyBrick" },
      { palavra: "Comer", icone: "Apple" },
      { palavra: "Dormir", icone: "Moon" },
      { palavra: "Escovar os dentes", icone: "Sparkles" },
      { palavra: "Passear", icone: "TreePalm" },
    ],
  },
  {
    slug: "perguntas-e-respostas",
    numero: 3,
    titulo: "Jogo de Perguntas e Respostas",
    categoriaSlug: "linguagem-oral",
    objetivo: "Trabalhar a compreensão e a formulação de respostas a perguntas do tipo 'o quê', 'quem' e 'onde'.",
    materiais: ["Cartões de perguntas", "Cartões de figuras de apoio"],
    comoPreparar: [
      "Imprima e recorte os cartões de perguntas.",
      "Separe figuras que ajudem a responder cada pergunta.",
    ],
    comoAplicar: [
      "Sorteie um cartão de pergunta e leia em voz alta.",
      "Dê tempo para a criança pensar e responder.",
      "Use as figuras de apoio quando ela tiver dificuldade.",
      "Reforce a resposta correta repetindo a frase completa.",
    ],
    variacao: "Inverta os papéis: a criança faz as perguntas e você responde (às vezes errando de propósito).",
  },

  // ---------------- Vocabulário e categorias ----------------
  {
    slug: "grupos-e-categorias",
    numero: 4,
    titulo: "Grupos e Categorias",
    categoriaSlug: "vocabulario-categorias",
    objetivo: "Ampliar o vocabulário e a capacidade de agrupar palavras por categorias semânticas.",
    materiais: ["Cartões de figuras variadas", "Cartelas de categorias (animais, frutas, roupas, brinquedos)"],
    comoPreparar: [
      "Imprima e recorte os cartões de figuras.",
      "Disponha as cartelas de categorias sobre a mesa.",
    ],
    comoAplicar: [
      "Mostre um cartão e pergunte: 'A que grupo isso pertence?'.",
      "A criança coloca o cartão na cartela correta.",
      "Peça para ela nomear a figura e a categoria em voz alta.",
      "Ao final, conte juntos quantos itens há em cada grupo.",
    ],
    variacao: "Peça para a criança lembrar de mais um item de cada categoria sem usar os cartões.",
    cartoes: [
      { palavra: "Cachorro", icone: "Dog" },
      { palavra: "Gato", icone: "Cat" },
      { palavra: "Maçã", icone: "Apple" },
      { palavra: "Banana", icone: "Banana" },
      { palavra: "Camiseta", icone: "Shirt" },
      { palavra: "Sapato", icone: "Footprints" },
      { palavra: "Bola", icone: "CircleDot" },
      { palavra: "Urso", icone: "ToyBrick" },
    ],
  },
  {
    slug: "qual-e-o-diferente",
    numero: 5,
    titulo: "Qual é o Diferente?",
    categoriaSlug: "vocabulario-categorias",
    objetivo: "Desenvolver o raciocínio categorial identificando o item que não pertence ao grupo.",
    materiais: ["Cartelas com quatro figuras (três da mesma categoria e uma diferente)"],
    comoPreparar: ["Imprima as cartelas.", "Tenha um lápis ou marcador para circular a resposta."],
    comoAplicar: [
      "Mostre uma cartela com quatro figuras.",
      "Pergunte: 'Qual é o diferente?'.",
      "A criança circula ou aponta a figura que não combina.",
      "Pergunte por que ela escolheu aquele item, estimulando a justificativa.",
    ],
    variacao: "Aumente o desafio usando categorias mais próximas, como frutas e legumes.",
    cartoes: [
      { palavra: "Maçã", icone: "Apple" },
      { palavra: "Banana", icone: "Banana" },
      { palavra: "Uva", icone: "Grape" },
      { palavra: "Carro", icone: "Car" },
    ],
  },
  {
    slug: "caca-aos-objetos",
    numero: 6,
    titulo: "Caça aos Objetos",
    categoriaSlug: "vocabulario-categorias",
    objetivo: "Estimular a nomeação e a busca de objetos por características e funções.",
    materiais: ["Lista de pistas impressa", "Objetos ou figuras espalhados pela sala"],
    comoPreparar: [
      "Imprima a lista de pistas.",
      "Espalhe alguns objetos ou figuras pelo ambiente.",
    ],
    comoAplicar: [
      "Dê uma pista de função: 'Procure algo que serve para comer'.",
      "A criança encontra e nomeia o objeto.",
      "Peça para ela explicar para que o objeto serve.",
      "Repita com pistas de cor, tamanho e formato.",
    ],
    variacao: "A criança dá as pistas e você procura, invertendo os papéis.",
  },

  // ---------------- Fala e articulação ----------------
  {
    slug: "repita-comigo",
    numero: 7,
    titulo: "Repita Comigo",
    categoriaSlug: "fala-articulacao",
    objetivo: "Treinar a produção de fonemas-alvo em palavras isoladas com apoio de figuras.",
    materiais: ["Cartões de palavras com o fonema-alvo", "Espelho de mão (opcional)"],
    comoPreparar: [
      "Selecione os cartões com o fonema que está trabalhando.",
      "Posicione o espelho para a criança observar a boca.",
    ],
    comoAplicar: [
      "Mostre o cartão e fale a palavra pausadamente.",
      "Peça para a criança repetir, observando o ponto articulatório.",
      "Reforce as produções corretas e ajuste suavemente as demais.",
      "Faça três repetições de cada palavra.",
    ],
    variacao: "Use as palavras em frases curtas depois que o som estiver estável.",
    cartoes: [
      { palavra: "Bola", icone: "CircleDot" },
      { palavra: "Pato", icone: "Bird" },
      { palavra: "Sapo", icone: "Rabbit" },
      { palavra: "Gato", icone: "Cat" },
      { palavra: "Faca", icone: "Utensils" },
      { palavra: "Rato", icone: "Mouse" },
    ],
  },
  {
    slug: "caminho-dos-sons",
    numero: 8,
    titulo: "Caminho dos Sons",
    categoriaSlug: "fala-articulacao",
    objetivo: "Praticar a articulação de sílabas de forma lúdica em um jogo de tabuleiro.",
    materiais: ["Tabuleiro do caminho impresso", "Dado", "Peões ou tampinhas"],
    comoPreparar: [
      "Imprima o tabuleiro do caminho.",
      "Separe o dado e os peões.",
    ],
    comoAplicar: [
      "A criança joga o dado e anda as casas indicadas.",
      "Ao parar em uma casa, ela fala a sílaba ou palavra daquela casa.",
      "Pronuncie junto sempre que necessário.",
      "Vence quem chegar primeiro ao final do caminho.",
    ],
    variacao: "Troque as sílabas do tabuleiro conforme o fonema que estiver trabalhando.",
    cartoes: [
      { palavra: "PA", icone: "Volume2" },
      { palavra: "PE", icone: "Volume2" },
      { palavra: "PI", icone: "Volume2" },
      { palavra: "PO", icone: "Volume2" },
      { palavra: "PU", icone: "Volume2" },
      { palavra: "BA", icone: "Volume2" },
      { palavra: "BE", icone: "Volume2" },
      { palavra: "BI", icone: "Volume2" },
    ],
  },
  {
    slug: "roda-das-palavras",
    numero: 9,
    titulo: "Roda das Palavras",
    categoriaSlug: "fala-articulacao",
    objetivo: "Estimular vocabulário, agilidade e articulação por meio de uma roleta de categorias.",
    materiais: ["Roleta de categorias impressa", "Prendedor ou seta giratória"],
    comoPreparar: [
      "Imprima a roleta e monte a seta giratória no centro.",
      "Defina as categorias de cada fatia (frutas, animais, ações, objetos).",
    ],
    comoAplicar: [
      "A criança gira a seta e observa em qual categoria parou.",
      "Ela deve dizer uma palavra daquela categoria, articulando bem.",
      "Anote ou conte os pontos a cada acerto.",
      "Faça várias rodadas, aumentando o ritmo aos poucos.",
    ],
    variacao: "Peça duas ou três palavras por categoria para crianças com mais repertório.",
    cartoes: [
      { palavra: "Frutas", icone: "Apple" },
      { palavra: "Animais", icone: "PawPrint" },
      { palavra: "Ações", icone: "Zap" },
      { palavra: "Objetos", icone: "Box" },
      { palavra: "Alimentos", icone: "Utensils" },
      { palavra: "Cores", icone: "Palette" },
    ],
  },

  // ---------------- Consciência fonológica ----------------
  {
    slug: "quantas-silabas",
    numero: 10,
    titulo: "Quantas Sílabas?",
    categoriaSlug: "consciencia-fonologica",
    objetivo: "Desenvolver a consciência silábica por meio da contagem de sílabas das palavras.",
    materiais: ["Cartões de figuras", "Fichas ou tampinhas para marcar as sílabas"],
    comoPreparar: [
      "Imprima e recorte os cartões de figuras.",
      "Separe fichas para representar cada sílaba.",
    ],
    comoAplicar: [
      "Mostre uma figura e nomeie a palavra.",
      "Bata palmas para cada sílaba: ca-sa (duas palmas).",
      "A criança repete batendo palmas e conta as sílabas.",
      "Ela coloca uma ficha para cada sílaba contada.",
    ],
    variacao: "Peça para a criança encontrar duas palavras que tenham o mesmo número de sílabas.",
    cartoes: [
      { palavra: "Casa", icone: "House" },
      { palavra: "Boneca", icone: "Baby" },
      { palavra: "Sol", icone: "Sun" },
      { palavra: "Borboleta", icone: "Bug" },
      { palavra: "Pato", icone: "Bird" },
      { palavra: "Sapato", icone: "Footprints" },
    ],
  },
  {
    slug: "som-inicial",
    numero: 11,
    titulo: "Som Inicial",
    categoriaSlug: "consciencia-fonologica",
    objetivo: "Trabalhar a identificação do som inicial das palavras, base para a alfabetização.",
    materiais: ["Cartões de figuras", "Cartelas de letras"],
    comoPreparar: [
      "Imprima as figuras e as cartelas de letras.",
      "Organize as letras-alvo sobre a mesa.",
    ],
    comoAplicar: [
      "Mostre uma figura e fale a palavra enfatizando o primeiro som.",
      "Pergunte: 'Com que som essa palavra começa?'.",
      "A criança coloca a figura embaixo da letra correta.",
      "Repita com palavras que começam com sons diferentes.",
    ],
    variacao: "Trabalhe também o som final das palavras para crianças mais avançadas.",
    cartoes: [
      { palavra: "Abelha", icone: "Bug" },
      { palavra: "Bola", icone: "CircleDot" },
      { palavra: "Casa", icone: "House" },
      { palavra: "Dado", icone: "Dice5" },
      { palavra: "Elefante", icone: "PawPrint" },
      { palavra: "Foca", icone: "Fish" },
    ],
  },
  {
    slug: "rimas-divertidas",
    numero: 12,
    titulo: "Rimas Divertidas",
    categoriaSlug: "consciencia-fonologica",
    objetivo: "Estimular a percepção de rimas, identificando palavras com sons finais semelhantes.",
    materiais: ["Cartões de figuras que rimam", "Bandeja para os pares"],
    comoPreparar: [
      "Imprima os cartões de figuras que formam pares de rimas.",
      "Embaralhe os cartões antes de começar.",
    ],
    comoAplicar: [
      "Espalhe os cartões com a figura para cima.",
      "Fale duas palavras e pergunte se elas rimam.",
      "A criança procura as figuras que rimam e forma pares.",
      "Diga as rimas em voz alta juntos para confirmar.",
    ],
    variacao: "Peça para a criança inventar uma nova palavra que rime, mesmo que seja inventada.",
    cartoes: [
      { palavra: "Pão", icone: "Cookie" },
      { palavra: "Mão", icone: "Hand" },
      { palavra: "Gato", icone: "Cat" },
      { palavra: "Pato", icone: "Bird" },
      { palavra: "Bola", icone: "CircleDot" },
      { palavra: "Sacola", icone: "ShoppingBag" },
    ],
  },

  // ---------------- Atenção e memória auditiva ----------------
  {
    slug: "memoria-dos-sons",
    numero: 13,
    titulo: "Memória dos Sons",
    categoriaSlug: "atencao-memoria",
    objetivo: "Trabalhar a memória auditiva por meio da repetição de sequências de palavras.",
    materiais: ["Cartões de figuras", "Ambiente tranquilo, sem distrações"],
    comoPreparar: [
      "Selecione os cartões de figuras.",
      "Garanta um ambiente sem ruídos para a tarefa.",
    ],
    comoAplicar: [
      "Fale uma sequência de duas palavras e peça para a criança repetir.",
      "Aumente gradualmente para três e quatro palavras.",
      "Use os cartões como apoio caso ela esqueça.",
      "Comemore cada sequência repetida corretamente.",
    ],
    variacao: "Peça para a criança repetir a sequência na ordem inversa.",
    cartoes: [
      { palavra: "Sol", icone: "Sun" },
      { palavra: "Casa", icone: "House" },
      { palavra: "Bola", icone: "CircleDot" },
      { palavra: "Flor", icone: "Flower2" },
      { palavra: "Carro", icone: "Car" },
      { palavra: "Estrela", icone: "Star" },
    ],
  },
  {
    slug: "escute-e-aponte",
    numero: 14,
    titulo: "Escute e Aponte",
    categoriaSlug: "atencao-memoria",
    objetivo: "Desenvolver a atenção auditiva e a associação entre o que se ouve e a figura correspondente.",
    materiais: ["Painel com várias figuras", "Lista de comandos"],
    comoPreparar: [
      "Imprima o painel com as figuras.",
      "Tenha em mãos a lista de comandos.",
    ],
    comoAplicar: [
      "Fale o nome de uma figura e peça para a criança apontar.",
      "Dê comandos com duas figuras: 'Aponte o sol e depois a bola'.",
      "Aumente a quantidade de figuras nos comandos.",
      "Reforce a atenção pedindo para ela esperar o comando terminar.",
    ],
    variacao: "Inclua comandos com posição: 'Aponte a figura que está ao lado do gato'.",
    cartoes: [
      { palavra: "Sol", icone: "Sun" },
      { palavra: "Bola", icone: "CircleDot" },
      { palavra: "Gato", icone: "Cat" },
      { palavra: "Flor", icone: "Flower2" },
      { palavra: "Peixe", icone: "Fish" },
      { palavra: "Carro", icone: "Car" },
    ],
  },
  {
    slug: "siga-o-comando",
    numero: 15,
    titulo: "Siga o Comando",
    categoriaSlug: "atencao-memoria",
    objetivo: "Trabalhar a compreensão de ordens e a memória de instruções em sequência.",
    materiais: ["Lista de comandos impressa", "Objetos simples da sala"],
    comoPreparar: [
      "Imprima a lista de comandos.",
      "Deixe alguns objetos ao alcance da criança.",
    ],
    comoAplicar: [
      "Dê um comando simples: 'Pegue o lápis'.",
      "Aumente para dois passos: 'Pegue o lápis e coloque na caixa'.",
      "Avance para três passos conforme a criança acerta.",
      "Peça para ela repetir o comando antes de executar.",
    ],
    variacao: "Transforme em brincadeira de 'mestre mandou' para crianças mais ativas.",
  },

  // ---------------- Sequência lógica e narrativa ----------------
  {
    slug: "conte-a-historia",
    numero: 16,
    titulo: "Conte a História",
    categoriaSlug: "sequencia-narrativa",
    objetivo: "Desenvolver a narrativa organizando cenas em sequência lógica e contando a história.",
    materiais: ["Cartões de cenas em sequência", "Mesa ou superfície para ordenar"],
    comoPreparar: [
      "Imprima e recorte os cartões de cenas.",
      "Embaralhe os cartões antes de entregar.",
    ],
    comoAplicar: [
      "Entregue os cartões embaralhados de uma história.",
      "Peça para a criança colocar as cenas na ordem certa.",
      "Ela conta a história apontando para cada cena.",
      "Pergunte sobre o início, o meio e o fim.",
    ],
    variacao: "Peça para ela criar um final diferente para a mesma história.",
    cartoes: [
      { palavra: "Primeiro", icone: "CircleDot" },
      { palavra: "Depois", icone: "ArrowRight" },
      { palavra: "Então", icone: "ArrowRight" },
      { palavra: "Por fim", icone: "Flag" },
    ],
  },
  {
    slug: "o-que-vem-depois",
    numero: 17,
    titulo: "O que Vem Depois?",
    categoriaSlug: "sequencia-narrativa",
    objetivo: "Trabalhar a noção de sequência temporal usando rotinas do dia a dia.",
    materiais: ["Cartões de rotina diária", "Trilho ou linha para ordenar"],
    comoPreparar: [
      "Imprima os cartões de rotina.",
      "Desenhe uma linha do tempo simples no papel.",
    ],
    comoAplicar: [
      "Mostre um cartão de rotina, por exemplo 'acordar'.",
      "Pergunte: 'O que vem depois?'.",
      "A criança escolhe o próximo cartão e explica.",
      "Monte juntos a sequência completa do dia.",
    ],
    variacao: "Embaralhe a rotina e peça para a criança corrigir a ordem errada.",
    cartoes: [
      { palavra: "Acordar", icone: "Sun" },
      { palavra: "Café da manhã", icone: "Coffee" },
      { palavra: "Escola", icone: "Backpack" },
      { palavra: "Almoço", icone: "Utensils" },
      { palavra: "Banho", icone: "Bath" },
      { palavra: "Dormir", icone: "Moon" },
    ],
  },
  {
    slug: "causa-e-efeito",
    numero: 18,
    titulo: "Causa e Efeito",
    categoriaSlug: "sequencia-narrativa",
    objetivo: "Estimular o raciocínio lógico relacionando uma situação à sua consequência.",
    materiais: ["Cartões de causa", "Cartões de efeito"],
    comoPreparar: [
      "Imprima e separe os cartões de causa e de efeito.",
      "Embaralhe cada grupo separadamente.",
    ],
    comoAplicar: [
      "Mostre um cartão de causa: 'A criança soltou o sorvete'.",
      "Pergunte: 'O que acontece depois?'.",
      "A criança procura o cartão de efeito correspondente.",
      "Ela explica a relação entre a causa e o efeito.",
    ],
    variacao: "Peça para a criança imaginar mais de um efeito possível para a mesma causa.",
  },
  {
    slug: "descreva-a-figura",
    numero: 19,
    titulo: "Descreva a Figura",
    categoriaSlug: "linguagem-oral",
    objetivo: "Ampliar o discurso descritivo, levando a criança a falar sobre cor, tamanho, partes e função do que vê.",
    materiais: ["Cartões de figuras grandes", "Lista de perguntas de apoio"],
    comoPreparar: ["Imprima e recorte os cartões de figuras.", "Tenha as perguntas de apoio à mão."],
    comoAplicar: [
      "A criança escolhe um cartão e observa a figura.",
      "Pergunte sobre cor, tamanho e para que serve.",
      "Incentive frases completas em vez de respostas de uma palavra.",
      "Acrescente um detalhe novo à descrição dela.",
    ],
    variacao: "Esconda a figura e peça para a criança descrevê-la de memória.",
    cartoes: [
      { palavra: "Carro", icone: "Car" },
      { palavra: "Flor", icone: "Flower2" },
      { palavra: "Gato", icone: "Cat" },
      { palavra: "Casa", icone: "House" },
      { palavra: "Maçã", icone: "Apple" },
      { palavra: "Sol", icone: "Sun" },
    ],
  },
  {
    slug: "quem-sou-eu",
    numero: 20,
    titulo: "Quem Sou Eu?",
    categoriaSlug: "linguagem-oral",
    objetivo: "Desenvolver a compreensão por pistas e a linguagem dedutiva por meio de adivinhas descritivas.",
    materiais: ["Cartões de figuras", "Lista de pistas impressa"],
    comoPreparar: ["Imprima as figuras e as pistas.", "Mantenha os cartões virados para baixo."],
    comoAplicar: [
      "Dê pistas: 'Sou um animal, faço au-au e gosto de osso'.",
      "A criança tenta adivinhar a figura.",
      "Confirme mostrando o cartão correspondente.",
      "Peça para ela criar pistas para você adivinhar.",
    ],
    variacao: "Use categorias mais abstratas, como profissões ou meios de transporte.",
    cartoes: [
      { palavra: "Cachorro", icone: "Dog" },
      { palavra: "Peixe", icone: "Fish" },
      { palavra: "Avião", icone: "Plane" },
      { palavra: "Banana", icone: "Banana" },
    ],
  },
  {
    slug: "complete-a-frase",
    numero: 21,
    titulo: "Complete a Frase",
    categoriaSlug: "linguagem-oral",
    objetivo: "Estimular o fechamento de frases e o uso de vocabulário em contexto.",
    materiais: ["Cartões de frases inacabadas", "Figuras de apoio"],
    comoPreparar: ["Imprima os cartões de frases.", "Separe figuras que ajudem a completar."],
    comoAplicar: [
      "Leia uma frase deixando o final em aberto: 'Eu durmo na...'.",
      "A criança completa com a palavra que faz sentido.",
      "Use as figuras como apoio quando necessário.",
      "Repita a frase completa para reforçar.",
    ],
    variacao: "Peça mais de uma palavra possível para completar a mesma frase.",
  },
  {
    slug: "conversa-ao-telefone",
    numero: 22,
    titulo: "Conversa ao Telefone",
    categoriaSlug: "linguagem-oral",
    objetivo: "Praticar turnos de conversa, perguntas e respostas em um diálogo simulado.",
    materiais: ["Dois telefones de brinquedo (ou de papel)", "Lista de temas de conversa"],
    comoPreparar: ["Monte os telefones de brinquedo.", "Escolha um tema simples para a conversa."],
    comoAplicar: [
      "Simule uma ligação: 'Alô, tudo bem?'.",
      "Espere a criança responder e fazer a próxima pergunta.",
      "Respeitem os turnos de falar e escutar.",
      "Encerrem a ligação com uma despedida.",
    ],
    variacao: "Combine papéis: pizzaria, médico ou loja, ampliando o vocabulário.",
  },
  {
    slug: "fale-sobre-o-seu-dia",
    numero: 23,
    titulo: "Fale sobre o seu Dia",
    categoriaSlug: "linguagem-oral",
    objetivo: "Desenvolver o relato de eventos pessoais com início, meio e fim.",
    materiais: ["Cartões de momentos do dia", "Linha do tempo de papel"],
    comoPreparar: ["Imprima os cartões de momentos.", "Desenhe uma linha do tempo simples."],
    comoAplicar: [
      "Pergunte o que a criança fez ao acordar.",
      "Use os cartões para marcar cada momento na linha do tempo.",
      "Estimule conectivos: 'primeiro', 'depois', 'no fim'.",
      "Ajude-a a contar o dia inteiro em ordem.",
    ],
    variacao: "Peça para ela contar o dia de um personagem ou de um familiar.",
    cartoes: [
      { palavra: "Acordar", icone: "Sun" },
      { palavra: "Escola", icone: "Backpack" },
      { palavra: "Almoço", icone: "Utensils" },
      { palavra: "Brincar", icone: "ToyBrick" },
      { palavra: "Banho", icone: "Bath" },
      { palavra: "Dormir", icone: "Moon" },
    ],
  },
  {
    slug: "o-que-voce-faria",
    numero: 24,
    titulo: "O que Você Faria?",
    categoriaSlug: "linguagem-oral",
    objetivo: "Trabalhar a linguagem em situações sociais e a resolução verbal de problemas.",
    materiais: ["Cartões de situações do dia a dia"],
    comoPreparar: ["Imprima os cartões de situações.", "Leia cada situação antes de começar."],
    comoAplicar: [
      "Apresente uma situação: 'Você derrubou o lápis do amigo'.",
      "Pergunte: 'O que você faria?'.",
      "Valorize respostas que mostrem solução e empatia.",
      "Converse sobre outras formas de resolver.",
    ],
    variacao: "Encene a situação com bonecos para crianças mais novas.",
  },
  {
    slug: "pergunte-ao-amigo",
    numero: 25,
    titulo: "Pergunte ao Amigo",
    categoriaSlug: "linguagem-oral",
    objetivo: "Estimular a formulação de perguntas, habilidade essencial para a conversa.",
    materiais: ["Cartões com início de perguntas (quem, o quê, onde, quando)"],
    comoPreparar: ["Imprima os cartões com as palavras de pergunta.", "Escolha um tema para as perguntas."],
    comoAplicar: [
      "A criança sorteia uma palavra de pergunta.",
      "Ela cria uma pergunta usando essa palavra.",
      "Você responde e devolve uma nova pergunta.",
      "Alternem perguntando e respondendo.",
    ],
    variacao: "Use um tema fixo, como animais, para direcionar as perguntas.",
  },
  {
    slug: "reconto-da-historinha",
    numero: 26,
    titulo: "Recontando a Historinha",
    categoriaSlug: "linguagem-oral",
    objetivo: "Trabalhar a memória de narrativa e o reconto com sequência lógica.",
    materiais: ["Um livro ou história curta", "Cartões das cenas principais"],
    comoPreparar: ["Escolha uma história curta.", "Separe os cartões das cenas principais."],
    comoAplicar: [
      "Conte a história uma vez de forma animada.",
      "Embaralhe os cartões das cenas e peça para ordenar.",
      "A criança reconta a história com suas palavras.",
      "Pergunte sobre os personagens e o que aconteceu.",
    ],
    variacao: "Peça para a criança recontar como se fosse um dos personagens.",
  },
  {
    slug: "para-que-serve",
    numero: 27,
    titulo: "Para que Serve?",
    categoriaSlug: "linguagem-oral",
    objetivo: "Ampliar o vocabulário de função, relacionando objetos ao seu uso.",
    materiais: ["Cartões de objetos do cotidiano"],
    comoPreparar: ["Imprima e recorte os cartões de objetos.", "Deixe os cartões à vista."],
    comoAplicar: [
      "Mostre um objeto e pergunte: 'Para que serve?'.",
      "A criança explica a função em uma frase.",
      "Pergunte onde costumamos usar aquele objeto.",
      "Acrescente um uso diferente do mesmo objeto.",
    ],
    variacao: "Inverta: diga a função e a criança descobre o objeto.",
    cartoes: [
      { palavra: "Colher", icone: "Utensils" },
      { palavra: "Escova", icone: "Sparkles" },
      { palavra: "Lápis", icone: "Pencil" },
      { palavra: "Guarda-chuva", icone: "Umbrella" },
      { palavra: "Chave", icone: "Key" },
      { palavra: "Copo", icone: "CupSoda" },
    ],
  },
  {
    slug: "de-uma-ordem",
    numero: 28,
    titulo: "Dê uma Ordem",
    categoriaSlug: "linguagem-oral",
    objetivo: "Trabalhar verbos de ação e a estrutura de frases imperativas.",
    materiais: ["Cartões de verbos de ação"],
    comoPreparar: ["Imprima os cartões de ações.", "Combine um espaço livre para se movimentar."],
    comoAplicar: [
      "A criança sorteia um cartão de ação, por exemplo 'pular'.",
      "Ela dá a ordem em voz alta: 'Pule três vezes!'.",
      "Você executa a ação combinada.",
      "Troquem de papéis a cada rodada.",
    ],
    variacao: "Junte duas ações na mesma ordem para aumentar o desafio.",
    cartoes: [
      { palavra: "Pular", icone: "Rabbit" },
      { palavra: "Correr", icone: "Footprints" },
      { palavra: "Bater palmas", icone: "Hand" },
      { palavra: "Girar", icone: "RefreshCw" },
      { palavra: "Sentar", icone: "Armchair" },
      { palavra: "Abraçar", icone: "Heart" },
    ],
  },
  {
    slug: "eu-vejo-algo",
    numero: 29,
    titulo: "Eu Vejo Algo...",
    categoriaSlug: "linguagem-oral",
    objetivo: "Estimular a descrição por características e a atenção ao ambiente.",
    materiais: ["Apenas o ambiente da sala", "Lista de características de apoio"],
    comoPreparar: ["Observe o ambiente e escolha objetos visíveis.", "Tenha pistas de cor e forma prontas."],
    comoAplicar: [
      "Diga: 'Eu vejo algo vermelho e redondo'.",
      "A criança procura e nomeia o objeto.",
      "Confirme e peça para ela descrever melhor.",
      "Agora é a vez de a criança dar a pista.",
    ],
    variacao: "Use pistas de função: 'Eu vejo algo que serve para escrever'.",
  },
  {
    slug: "concordar-ou-discordar",
    numero: 30,
    titulo: "Concordar ou Discordar",
    categoriaSlug: "linguagem-oral",
    objetivo: "Trabalhar o julgamento de frases e a justificativa verbal.",
    materiais: ["Cartões de afirmações simples"],
    comoPreparar: ["Imprima os cartões de afirmações.", "Combine sinais para 'sim' e 'não'."],
    comoAplicar: [
      "Leia uma afirmação: 'O gato late'.",
      "A criança diz se concorda ou discorda.",
      "Peça para ela explicar o porquê.",
      "Corrijam juntos as afirmações erradas.",
    ],
    variacao: "Use afirmações engraçadas e absurdas para divertir e engajar.",
  },
  {
    slug: "termine-a-ideia",
    numero: 31,
    titulo: "Termine a Ideia",
    categoriaSlug: "linguagem-oral",
    objetivo: "Estimular o raciocínio verbal e o uso de causa em frases mais longas.",
    materiais: ["Cartões de frases com 'porque' em aberto"],
    comoPreparar: ["Imprima os cartões de frases.", "Leia uma frase de exemplo antes de iniciar."],
    comoAplicar: [
      "Leia: 'Eu coloquei o casaco porque...'.",
      "A criança termina a ideia com uma explicação.",
      "Valorize respostas que façam sentido.",
      "Ofereça mais de um final possível.",
    ],
    variacao: "Troque 'porque' por 'então' para trabalhar consequência.",
  },
  {
    slug: "mimica-falada",
    numero: 32,
    titulo: "Mímica Falada",
    categoriaSlug: "linguagem-oral",
    objetivo: "Unir gesto e linguagem, descrevendo ações para que sejam adivinhadas.",
    materiais: ["Cartões de ações do dia a dia"],
    comoPreparar: ["Imprima os cartões de ações.", "Deixe espaço para gesticular."],
    comoAplicar: [
      "A criança sorteia uma ação e a representa com o corpo.",
      "Ao mesmo tempo, ela descreve com palavras o que faz.",
      "Você adivinha a ação representada.",
      "Invertam os papéis na próxima rodada.",
    ],
    variacao: "Faça apenas com a fala, sem gestos, para focar na descrição.",
    cartoes: [
      { palavra: "Escovar dentes", icone: "Sparkles" },
      { palavra: "Comer", icone: "Utensils" },
      { palavra: "Dormir", icone: "Moon" },
      { palavra: "Dirigir", icone: "Car" },
      { palavra: "Nadar", icone: "Waves" },
      { palavra: "Pentear", icone: "Sparkles" },
    ],
  },
  {
    slug: "pares-que-combinam",
    numero: 33,
    titulo: "Pares que Combinam",
    categoriaSlug: "vocabulario-categorias",
    objetivo: "Trabalhar associação semântica unindo itens que se relacionam por uso ou função.",
    materiais: ["Cartões de objetos que formam pares (escova e pasta, sapato e meia)"],
    comoPreparar: ["Imprima e recorte os pares.", "Embaralhe todos os cartões."],
    comoAplicar: [
      "Espalhe os cartões com a figura para cima.",
      "A criança procura os pares que combinam.",
      "Ela explica por que os dois itens combinam.",
      "Conte juntos quantos pares foram formados.",
    ],
    variacao: "Aumente o desafio com pares menos óbvios, como chuva e guarda-chuva.",
    cartoes: [
      { palavra: "Escova", icone: "Sparkles" },
      { palavra: "Pasta", icone: "Sparkles" },
      { palavra: "Sapato", icone: "Footprints" },
      { palavra: "Meia", icone: "Footprints" },
      { palavra: "Chuva", icone: "CloudRain" },
      { palavra: "Guarda-chuva", icone: "Umbrella" },
    ],
  },
  {
    slug: "antonimos-opostos",
    numero: 34,
    titulo: "Os Opostos",
    categoriaSlug: "vocabulario-categorias",
    objetivo: "Ampliar o vocabulário trabalhando antônimos e conceitos contrários.",
    materiais: ["Cartões de pares de opostos (grande/pequeno, alto/baixo)"],
    comoPreparar: ["Imprima os cartões de opostos.", "Separe os pares antes de começar."],
    comoAplicar: [
      "Mostre uma figura, por exemplo 'grande'.",
      "Pergunte: 'Qual é o contrário?'.",
      "A criança procura ou nomeia o oposto.",
      "Use os dois em uma frase para fixar.",
    ],
    variacao: "Brinque de falar o oposto rapidamente, sem usar os cartões.",
    cartoes: [
      { palavra: "Grande", icone: "Maximize" },
      { palavra: "Pequeno", icone: "Minimize" },
      { palavra: "Quente", icone: "Flame" },
      { palavra: "Frio", icone: "Snowflake" },
      { palavra: "Dia", icone: "Sun" },
      { palavra: "Noite", icone: "Moon" },
    ],
  },
  {
    slug: "palavras-parecidas",
    numero: 35,
    titulo: "Palavras Parecidas",
    categoriaSlug: "vocabulario-categorias",
    objetivo: "Trabalhar sinônimos e palavras de sentido próximo, enriquecendo o vocabulário.",
    materiais: ["Cartões de palavras com sentido parecido", "Figuras de apoio"],
    comoPreparar: ["Imprima os cartões.", "Leia um exemplo de palavras parecidas."],
    comoAplicar: [
      "Diga uma palavra, por exemplo 'feliz'.",
      "Pergunte: 'Que outra palavra quer dizer o mesmo?'.",
      "Ofereça opções como 'alegre' e 'contente'.",
      "Use as duas palavras em frases.",
    ],
    variacao: "Monte uma lista de palavras parecidas para uma mesma figura.",
  },
  {
    slug: "partes-do-corpo",
    numero: 36,
    titulo: "Partes do Corpo",
    categoriaSlug: "vocabulario-categorias",
    objetivo: "Nomear e localizar as partes do corpo, ampliando o vocabulário corporal.",
    materiais: ["Cartões das partes do corpo", "Um boneco ou espelho"],
    comoPreparar: ["Imprima os cartões das partes do corpo.", "Tenha o boneco ou espelho por perto."],
    comoAplicar: [
      "Mostre um cartão e nomeie a parte do corpo.",
      "A criança aponta a mesma parte em si ou no boneco.",
      "Peça para ela dizer para que serve aquela parte.",
      "Cante uma música apontando cada parte.",
    ],
    variacao: "Dê comandos: 'Toque o joelho e depois a orelha'.",
    cartoes: [
      { palavra: "Cabeça", icone: "User" },
      { palavra: "Mão", icone: "Hand" },
      { palavra: "Pé", icone: "Footprints" },
      { palavra: "Olho", icone: "Eye" },
      { palavra: "Orelha", icone: "Ear" },
      { palavra: "Boca", icone: "Smile" },
    ],
  },
  {
    slug: "profissoes-e-ferramentas",
    numero: 37,
    titulo: "Profissões e Ferramentas",
    categoriaSlug: "vocabulario-categorias",
    objetivo: "Associar profissões aos seus objetos de trabalho, ampliando vocabulário e função.",
    materiais: ["Cartões de profissões", "Cartões de ferramentas/objetos"],
    comoPreparar: ["Imprima os dois grupos de cartões.", "Embaralhe cada grupo separadamente."],
    comoAplicar: [
      "Mostre uma profissão, por exemplo 'médico'.",
      "A criança procura o objeto que combina (estetoscópio).",
      "Ela explica o que essa profissão faz.",
      "Repita com outras profissões.",
    ],
    variacao: "Pergunte onde cada profissional trabalha.",
    cartoes: [
      { palavra: "Médico", icone: "Stethoscope" },
      { palavra: "Cozinheiro", icone: "ChefHat" },
      { palavra: "Professor", icone: "BookOpen" },
      { palavra: "Bombeiro", icone: "Flame" },
      { palavra: "Pintor", icone: "Palette" },
      { palavra: "Motorista", icone: "Car" },
    ],
  },
  {
    slug: "meios-de-transporte",
    numero: 38,
    titulo: "Meios de Transporte",
    categoriaSlug: "vocabulario-categorias",
    objetivo: "Nomear meios de transporte e classificá-los por onde se movem.",
    materiais: ["Cartões de transportes", "Cartelas de terra, água e ar"],
    comoPreparar: ["Imprima os cartões e as cartelas.", "Disponha as cartelas na mesa."],
    comoAplicar: [
      "Mostre um transporte, por exemplo 'barco'.",
      "A criança diz se anda na terra, na água ou no ar.",
      "Ela coloca o cartão na cartela certa.",
      "Imite o som de cada transporte juntos.",
    ],
    variacao: "Pergunte quantas pessoas cabem em cada transporte.",
    cartoes: [
      { palavra: "Carro", icone: "Car" },
      { palavra: "Avião", icone: "Plane" },
      { palavra: "Barco", icone: "Sailboat" },
      { palavra: "Trem", icone: "TrainFront" },
      { palavra: "Bicicleta", icone: "Bike" },
      { palavra: "Ônibus", icone: "Bus" },
    ],
  },
  {
    slug: "frutas-e-verduras",
    numero: 39,
    titulo: "Frutas e Verduras",
    categoriaSlug: "vocabulario-categorias",
    objetivo: "Ampliar o vocabulário de alimentos e classificar em frutas e verduras.",
    materiais: ["Cartões de alimentos", "Duas cestas de papel (frutas e verduras)"],
    comoPreparar: ["Imprima os cartões de alimentos.", "Monte as duas cestas de papel."],
    comoAplicar: [
      "Mostre um alimento e peça para a criança nomear.",
      "Ela coloca na cesta de frutas ou de verduras.",
      "Pergunte a cor e o sabor de cada um.",
      "Conte quantos itens há em cada cesta.",
    ],
    variacao: "Inclua alimentos novos e converse sobre quais a criança já provou.",
    cartoes: [
      { palavra: "Maçã", icone: "Apple" },
      { palavra: "Banana", icone: "Banana" },
      { palavra: "Uva", icone: "Grape" },
      { palavra: "Cenoura", icone: "Carrot" },
      { palavra: "Alface", icone: "Salad" },
      { palavra: "Cereja", icone: "Cherry" },
    ],
  },
  {
    slug: "onde-cada-animal-vive",
    numero: 40,
    titulo: "Onde Cada Animal Vive",
    categoriaSlug: "vocabulario-categorias",
    objetivo: "Classificar animais por habitat, ampliando vocabulário e conhecimento de mundo.",
    materiais: ["Cartões de animais", "Cenários (fazenda, floresta, mar, casa)"],
    comoPreparar: ["Imprima os cartões e os cenários.", "Espalhe os cenários sobre a mesa."],
    comoAplicar: [
      "Mostre um animal, por exemplo 'peixe'.",
      "A criança diz onde ele vive e coloca no cenário.",
      "Pergunte o que esse animal come.",
      "Imitem o som e o movimento de cada animal.",
    ],
    variacao: "Pergunte quais animais poderiam viver em mais de um lugar.",
    cartoes: [
      { palavra: "Vaca", icone: "Beef" },
      { palavra: "Peixe", icone: "Fish" },
      { palavra: "Macaco", icone: "PawPrint" },
      { palavra: "Cachorro", icone: "Dog" },
      { palavra: "Pássaro", icone: "Bird" },
      { palavra: "Tartaruga", icone: "Shell" },
    ],
  },
  {
    slug: "cores-ao-redor",
    numero: 41,
    titulo: "Cores ao Redor",
    categoriaSlug: "vocabulario-categorias",
    objetivo: "Nomear cores e associá-las a objetos do ambiente.",
    materiais: ["Cartelas de cores", "Objetos coloridos da sala"],
    comoPreparar: ["Imprima as cartelas de cores.", "Separe objetos de cores variadas."],
    comoAplicar: [
      "Mostre uma cartela, por exemplo 'vermelho'.",
      "A criança procura algo daquela cor na sala.",
      "Ela nomeia o objeto e a cor.",
      "Agrupe os objetos por cor ao final.",
    ],
    variacao: "Peça duas cores ao mesmo tempo: 'algo azul e algo amarelo'.",
    cartoes: [
      { palavra: "Vermelho", icone: "Circle" },
      { palavra: "Azul", icone: "Circle" },
      { palavra: "Amarelo", icone: "Circle" },
      { palavra: "Verde", icone: "Circle" },
      { palavra: "Rosa", icone: "Circle" },
      { palavra: "Laranja", icone: "Circle" },
    ],
  },
  {
    slug: "formas-geometricas",
    numero: 42,
    titulo: "Formas Geométricas",
    categoriaSlug: "vocabulario-categorias",
    objetivo: "Reconhecer e nomear formas básicas, associando a objetos reais.",
    materiais: ["Cartões de formas", "Objetos com formas variadas"],
    comoPreparar: ["Imprima os cartões de formas.", "Reúna objetos redondos, quadrados e triangulares."],
    comoAplicar: [
      "Mostre uma forma, por exemplo 'círculo'.",
      "A criança procura um objeto com essa forma.",
      "Ela nomeia a forma e o objeto.",
      "Desenhem juntos a forma no ar.",
    ],
    variacao: "Monte um desenho usando várias formas recortadas.",
    cartoes: [
      { palavra: "Círculo", icone: "Circle" },
      { palavra: "Quadrado", icone: "Square" },
      { palavra: "Triângulo", icone: "Triangle" },
      { palavra: "Estrela", icone: "Star" },
      { palavra: "Coração", icone: "Heart" },
      { palavra: "Retângulo", icone: "RectangleHorizontal" },
    ],
  },
  {
    slug: "dentro-fora-embaixo",
    numero: 43,
    titulo: "Dentro, Fora e Embaixo",
    categoriaSlug: "vocabulario-categorias",
    objetivo: "Trabalhar conceitos espaciais e preposições por meio de comandos.",
    materiais: ["Uma caixa", "Um objeto pequeno (bola ou bicho de pelúcia)"],
    comoPreparar: ["Separe a caixa e o objeto.", "Combine os conceitos que serão treinados."],
    comoAplicar: [
      "Dê o comando: 'Coloque a bola dentro da caixa'.",
      "A criança executa e diz onde colocou.",
      "Varie com 'fora', 'embaixo', 'em cima' e 'ao lado'.",
      "Peça para ela dar os comandos para você.",
    ],
    variacao: "Use uma figura e pergunte onde está o objeto na imagem.",
  },
  {
    slug: "grande-ou-pequeno",
    numero: 44,
    titulo: "Grande ou Pequeno",
    categoriaSlug: "vocabulario-categorias",
    objetivo: "Trabalhar conceitos de tamanho e comparação entre objetos.",
    materiais: ["Cartões de objetos em tamanhos diferentes"],
    comoPreparar: ["Imprima os cartões.", "Separe pares do mesmo objeto em tamanhos diferentes."],
    comoAplicar: [
      "Mostre dois cartões do mesmo item.",
      "Pergunte: 'Qual é o grande e qual é o pequeno?'.",
      "A criança nomeia e compara.",
      "Ordene vários objetos do menor ao maior.",
    ],
    variacao: "Trabalhe também 'mais alto', 'mais baixo' e 'igual'.",
  },
  {
    slug: "os-comodos-da-casa",
    numero: 45,
    titulo: "Os Cômodos da Casa",
    categoriaSlug: "vocabulario-categorias",
    objetivo: "Nomear cômodos da casa e relacionar objetos a cada ambiente.",
    materiais: ["Cartões de cômodos", "Cartões de objetos da casa"],
    comoPreparar: ["Imprima os cartões de cômodos e objetos.", "Disponha os cômodos na mesa."],
    comoAplicar: [
      "Mostre um objeto, por exemplo 'cama'.",
      "A criança diz em qual cômodo ele fica.",
      "Ela coloca o objeto no cômodo certo.",
      "Pergunte o que mais existe naquele cômodo.",
    ],
    variacao: "Peça para a criança descrever o que faz em cada cômodo.",
    cartoes: [
      { palavra: "Cozinha", icone: "Utensils" },
      { palavra: "Quarto", icone: "Bed" },
      { palavra: "Banheiro", icone: "Bath" },
      { palavra: "Sala", icone: "Sofa" },
      { palavra: "Garagem", icone: "Car" },
      { palavra: "Jardim", icone: "Trees" },
    ],
  },
  {
    slug: "roupas-para-cada-tempo",
    numero: 46,
    titulo: "Roupas para Cada Tempo",
    categoriaSlug: "vocabulario-categorias",
    objetivo: "Relacionar vestuário ao clima, trabalhando vocabulário e raciocínio.",
    materiais: ["Cartões de roupas", "Cartões de clima (sol, chuva, frio)"],
    comoPreparar: ["Imprima os cartões de roupas e de clima.", "Separe os grupos."],
    comoAplicar: [
      "Mostre um clima, por exemplo 'frio'.",
      "A criança escolhe as roupas adequadas.",
      "Ela nomeia cada peça escolhida.",
      "Converse sobre por que usamos cada roupa.",
    ],
    variacao: "Vista um boneco de papel de acordo com o clima sorteado.",
    cartoes: [
      { palavra: "Casaco", icone: "Shirt" },
      { palavra: "Camiseta", icone: "Shirt" },
      { palavra: "Bota", icone: "Footprints" },
      { palavra: "Chapéu", icone: "HardHat" },
      { palavra: "Óculos de sol", icone: "Glasses" },
      { palavra: "Capa de chuva", icone: "Umbrella" },
    ],
  },
  {
    slug: "som-do-r",
    numero: 47,
    titulo: "Som do R",
    categoriaSlug: "fala-articulacao",
    objetivo: "Treinar a produção do fonema /R/ em palavras com apoio de figuras.",
    materiais: ["Cartões de palavras com R", "Espelho de mão"],
    comoPreparar: ["Selecione os cartões com o som R.", "Posicione o espelho para a criança ver a boca."],
    comoAplicar: [
      "Mostre o cartão e fale a palavra devagar.",
      "Peça para a criança repetir observando a língua.",
      "Reforce as produções corretas.",
      "Repita cada palavra três vezes.",
    ],
    variacao: "Use o R no meio e no fim das palavras conforme a evolução.",
    cartoes: [
      { palavra: "Rato", icone: "Mouse" },
      { palavra: "Rosa", icone: "Flower2" },
      { palavra: "Carro", icone: "Car" },
      { palavra: "Porta", icone: "DoorOpen" },
      { palavra: "Rua", icone: "Milestone" },
      { palavra: "Tigre", icone: "PawPrint" },
    ],
  },
  {
    slug: "som-do-s",
    numero: 48,
    titulo: "Som do S",
    categoriaSlug: "fala-articulacao",
    objetivo: "Treinar a produção do fonema /S/ em palavras isoladas.",
    materiais: ["Cartões de palavras com S", "Espelho de mão"],
    comoPreparar: ["Separe os cartões com o som S.", "Deixe o espelho ao alcance."],
    comoAplicar: [
      "Fale a palavra alongando o som do S.",
      "A criança repete prestando atenção ao sopro.",
      "Compare com o som certo no espelho.",
      "Faça repetições e comemore os acertos.",
    ],
    variacao: "Treine palavras com S em frases curtas depois.",
    cartoes: [
      { palavra: "Sapo", icone: "Rabbit" },
      { palavra: "Sol", icone: "Sun" },
      { palavra: "Sino", icone: "Bell" },
      { palavra: "Sapato", icone: "Footprints" },
      { palavra: "Casa", icone: "House" },
      { palavra: "Suco", icone: "CupSoda" },
    ],
  },
  {
    slug: "som-do-l",
    numero: 49,
    titulo: "Som do L",
    categoriaSlug: "fala-articulacao",
    objetivo: "Treinar a produção do fonema /L/ com apoio visual e articulatório.",
    materiais: ["Cartões de palavras com L", "Espelho de mão"],
    comoPreparar: ["Selecione os cartões com o som L.", "Posicione o espelho."],
    comoAplicar: [
      "Mostre onde a língua toca para fazer o L.",
      "Fale a palavra e peça para a criança repetir.",
      "Reforce a posição correta da língua.",
      "Repita cada palavra algumas vezes.",
    ],
    variacao: "Cante uma música cheia de palavras com L.",
    cartoes: [
      { palavra: "Lua", icone: "Moon" },
      { palavra: "Leão", icone: "PawPrint" },
      { palavra: "Bola", icone: "CircleDot" },
      { palavra: "Lápis", icone: "Pencil" },
      { palavra: "Luva", icone: "Hand" },
      { palavra: "Gelo", icone: "Snowflake" },
    ],
  },
  {
    slug: "som-do-ch",
    numero: 50,
    titulo: "Som do CH",
    categoriaSlug: "fala-articulacao",
    objetivo: "Treinar a produção do fonema /CH/ de forma lúdica.",
    materiais: ["Cartões de palavras com CH", "Espelho de mão"],
    comoPreparar: ["Separe os cartões com o som CH.", "Deixe o espelho por perto."],
    comoAplicar: [
      "Faça o som do CH como quem pede silêncio.",
      "Mostre a palavra e peça para a criança repetir.",
      "Observe os lábios arredondados no espelho.",
      "Reforce as produções corretas.",
    ],
    variacao: "Crie uma história cheia de palavras com CH.",
    cartoes: [
      { palavra: "Chave", icone: "Key" },
      { palavra: "Chuva", icone: "CloudRain" },
      { palavra: "Chapéu", icone: "HardHat" },
      { palavra: "Chá", icone: "Coffee" },
      { palavra: "Chão", icone: "Square" },
      { palavra: "Cachorro", icone: "Dog" },
    ],
  },
  {
    slug: "trava-linguas",
    numero: 51,
    titulo: "Trava-Línguas Divertidos",
    categoriaSlug: "fala-articulacao",
    objetivo: "Trabalhar agilidade articulatória e precisão da fala com frases desafiadoras.",
    materiais: ["Cartões de trava-línguas curtos", "Cronômetro (opcional)"],
    comoPreparar: ["Imprima os cartões de trava-línguas.", "Escolha um do nível da criança."],
    comoAplicar: [
      "Leia o trava-língua devagar, sílaba por sílaba.",
      "A criança repete no ritmo lento.",
      "Aumentem a velocidade aos poucos.",
      "Comemorem as repetições sem tropeços.",
    ],
    variacao: "Cronometre quem fala mais rápido sem errar.",
  },
  {
    slug: "sopro-magico",
    numero: 52,
    titulo: "Sopro Mágico",
    categoriaSlug: "fala-articulacao",
    objetivo: "Trabalhar o controle do sopro, importante para a respiração e a fala.",
    materiais: ["Bolinhas de papel", "Canudo", "Cata-vento ou penas"],
    comoPreparar: ["Separe as bolinhas de papel e o canudo.", "Defina uma linha de chegada na mesa."],
    comoAplicar: [
      "A criança sopra a bolinha pelo canudo até a chegada.",
      "Varie a força do sopro: forte e fraco.",
      "Sopre penas ou o cata-vento para diversificar.",
      "Faça pausas para respirar fundo entre as tentativas.",
    ],
    variacao: "Faça uma corrida de bolinhas sopradas entre você e a criança.",
  },
  {
    slug: "ginastica-da-boca",
    numero: 53,
    titulo: "Ginástica da Boca",
    categoriaSlug: "fala-articulacao",
    objetivo: "Trabalhar a mobilidade dos órgãos da fala com exercícios orofaciais lúdicos.",
    materiais: ["Cartões de movimentos (mandar beijo, estalar a língua)", "Espelho"],
    comoPreparar: ["Imprima os cartões de movimentos.", "Posicione o espelho de frente."],
    comoAplicar: [
      "A criança sorteia um cartão de movimento.",
      "Vocês fazem o movimento juntos no espelho.",
      "Repitam cada movimento cinco vezes.",
      "Misturem os movimentos numa sequência divertida.",
    ],
    variacao: "Transforme em uma música com os movimentos da boca.",
    cartoes: [
      { palavra: "Mandar beijo", icone: "Heart" },
      { palavra: "Estalar língua", icone: "Volume2" },
      { palavra: "Bochecha cheia", icone: "Smile" },
      { palavra: "Sorrir", icone: "Smile" },
      { palavra: "Beijo de peixe", icone: "Fish" },
      { palavra: "Língua pra cima", icone: "ArrowUp" },
    ],
  },
  {
    slug: "bingo-dos-sons",
    numero: 54,
    titulo: "Bingo dos Sons",
    categoriaSlug: "fala-articulacao",
    objetivo: "Treinar a produção de palavras com o fonema-alvo em um jogo de bingo.",
    materiais: ["Cartelas de bingo com figuras", "Marcadores ou tampinhas"],
    comoPreparar: ["Imprima as cartelas de bingo.", "Separe os marcadores."],
    comoAplicar: [
      "Sorteie uma figura e fale a palavra em voz alta.",
      "A criança repete a palavra e marca na cartela.",
      "Reforce a produção correta a cada palavra.",
      "Vence quem completar a cartela primeiro.",
    ],
    variacao: "Use cartelas só com palavras do fonema que está treinando.",
  },
  {
    slug: "palavra-na-frase",
    numero: 55,
    titulo: "Palavra dentro da Frase",
    categoriaSlug: "fala-articulacao",
    objetivo: "Generalizar a produção do som-alvo de palavras isoladas para frases.",
    materiais: ["Cartões de palavras com o som-alvo", "Modelos de frases"],
    comoPreparar: ["Selecione palavras já dominadas isoladamente.", "Tenha modelos de frases simples."],
    comoAplicar: [
      "A criança escolhe uma palavra com o som-alvo.",
      "Ela cria uma frase usando essa palavra.",
      "Reforce a produção correta dentro da frase.",
      "Aumente o tamanho das frases aos poucos.",
    ],
    variacao: "Peça duas palavras-alvo na mesma frase.",
  },
  {
    slug: "eco-das-silabas",
    numero: 56,
    titulo: "Eco das Sílabas",
    categoriaSlug: "fala-articulacao",
    objetivo: "Treinar a repetição precisa de sílabas, preparando a articulação de palavras.",
    materiais: ["Lista de sílabas-alvo impressa"],
    comoPreparar: ["Escolha as sílabas do fonema trabalhado.", "Organize da mais fácil para a mais difícil."],
    comoAplicar: [
      "Fale uma sílaba e peça para a criança repetir como um eco.",
      "Aumente para duas e três sílabas seguidas.",
      "Brinque de eco forte e eco fraquinho.",
      "Reforce a clareza de cada sílaba.",
    ],
    variacao: "Junte as sílabas treinadas para formar uma palavra.",
    cartoes: [
      { palavra: "PA-PA", icone: "Volume2" },
      { palavra: "TA-TE", icone: "Volume2" },
      { palavra: "LA-LE", icone: "Volume2" },
      { palavra: "MI-MO", icone: "Volume2" },
      { palavra: "SU-SO", icone: "Volume2" },
      { palavra: "RA-RE", icone: "Volume2" },
    ],
  },
  {
    slug: "cante-e-articule",
    numero: 57,
    titulo: "Cante e Articule",
    categoriaSlug: "fala-articulacao",
    objetivo: "Usar músicas conhecidas para treinar articulação de forma natural e divertida.",
    materiais: ["Lista de músicas infantis simples", "Figuras das palavras-chave"],
    comoPreparar: ["Escolha uma música curta e conhecida.", "Separe figuras das palavras principais."],
    comoAplicar: [
      "Cantem a música juntos devagar.",
      "Parem nas palavras-chave para articular bem.",
      "Apontem a figura ao cantar cada palavra.",
      "Repitam aumentando o ritmo aos poucos.",
    ],
    variacao: "Troque uma palavra da música por outra com o som-alvo.",
  },
  {
    slug: "caca-palavras-falado",
    numero: 58,
    titulo: "Caça-Palavras Falado",
    categoriaSlug: "fala-articulacao",
    objetivo: "Identificar e produzir figuras que contêm o fonema-alvo.",
    materiais: ["Painel com várias figuras", "Marcador"],
    comoPreparar: ["Imprima o painel com figuras variadas.", "Defina o som-alvo da atividade."],
    comoAplicar: [
      "Peça para a criança achar figuras com o som-alvo.",
      "Ela nomeia cada figura encontrada.",
      "Marque as figuras corretas no painel.",
      "Conte quantas palavras com o som ela achou.",
    ],
    variacao: "Cronometre para tornar a busca mais animada.",
  },
  {
    slug: "dado-dos-fonemas",
    numero: 59,
    titulo: "Dado dos Fonemas",
    categoriaSlug: "fala-articulacao",
    objetivo: "Treinar diferentes palavras-alvo conforme o resultado do dado.",
    materiais: ["Dado com figuras nas faces", "Cartões de palavras"],
    comoPreparar: ["Monte o dado com figuras.", "Separe os cartões de palavras."],
    comoAplicar: [
      "A criança joga o dado.",
      "Ela fala a palavra da figura que caiu para cima.",
      "Reforce a produção correta do som.",
      "Façam várias rodadas alternando.",
    ],
    variacao: "Peça para usar a palavra do dado em uma frase.",
  },
  {
    slug: "historias-com-o-som",
    numero: 60,
    titulo: "Histórias com o Som-Alvo",
    categoriaSlug: "fala-articulacao",
    objetivo: "Generalizar o som-alvo dentro de uma narrativa curta e contextualizada.",
    materiais: ["Cartões de figuras com o som-alvo", "Roteiro de história simples"],
    comoPreparar: ["Selecione figuras com o som trabalhado.", "Crie um roteiro curto com essas palavras."],
    comoAplicar: [
      "Conte uma história usando as palavras-alvo.",
      "Pause nas palavras para a criança falar.",
      "Ela aponta a figura ao dizer a palavra.",
      "Ao final, peça para ela recontar a história.",
    ],
    variacao: "Deixe a criança inventar a continuação da história.",
  },
  {
    slug: "junte-as-silabas",
    numero: 61,
    titulo: "Junte as Sílabas",
    categoriaSlug: "consciencia-fonologica",
    objetivo: "Desenvolver a síntese silábica, unindo sílabas para formar palavras.",
    materiais: ["Cartões de sílabas", "Figuras das palavras formadas"],
    comoPreparar: ["Imprima os cartões de sílabas.", "Separe as figuras correspondentes."],
    comoAplicar: [
      "Fale as sílabas separadas: ca... sa.",
      "A criança junta e descobre a palavra: casa.",
      "Ela aponta a figura correspondente.",
      "Aumente para palavras de três sílabas.",
    ],
    variacao: "Fale as sílabas mais devagar para crianças com dificuldade.",
    cartoes: [
      { palavra: "CA-SA", icone: "House" },
      { palavra: "BO-LA", icone: "CircleDot" },
      { palavra: "PA-TO", icone: "Bird" },
      { palavra: "GA-TO", icone: "Cat" },
      { palavra: "SA-PO", icone: "Rabbit" },
      { palavra: "DA-DO", icone: "Dice5" },
    ],
  },
  {
    slug: "separe-as-silabas",
    numero: 62,
    titulo: "Separe as Sílabas",
    categoriaSlug: "consciencia-fonologica",
    objetivo: "Trabalhar a segmentação silábica, dividindo palavras em sílabas.",
    materiais: ["Cartões de figuras", "Fichas para marcar sílabas"],
    comoPreparar: ["Imprima os cartões de figuras.", "Separe as fichas de marcação."],
    comoAplicar: [
      "Mostre uma figura e nomeie a palavra.",
      "Bata palmas separando as sílabas.",
      "A criança coloca uma ficha por sílaba.",
      "Conte quantas sílabas a palavra tem.",
    ],
    variacao: "Marche um passo para cada sílaba ao falar a palavra.",
    cartoes: [
      { palavra: "Boneca", icone: "Baby" },
      { palavra: "Janela", icone: "AppWindow" },
      { palavra: "Cavalo", icone: "PawPrint" },
      { palavra: "Sapato", icone: "Footprints" },
      { palavra: "Banana", icone: "Banana" },
      { palavra: "Tomate", icone: "Apple" },
    ],
  },
  {
    slug: "qual-comeca-igual",
    numero: 63,
    titulo: "Qual Começa Igual?",
    categoriaSlug: "consciencia-fonologica",
    objetivo: "Trabalhar a aliteração, identificando palavras com o mesmo som inicial.",
    materiais: ["Cartões de figuras agrupadas por som inicial"],
    comoPreparar: ["Imprima os cartões.", "Separe grupos com o mesmo som inicial."],
    comoAplicar: [
      "Fale uma palavra de referência, por exemplo 'bola'.",
      "Mostre figuras e pergunte qual começa igual.",
      "A criança escolhe a que tem o mesmo som inicial.",
      "Repitam o som inicial juntos para confirmar.",
    ],
    variacao: "Peça para a criança lembrar de mais uma palavra que comece igual.",
    cartoes: [
      { palavra: "Bola", icone: "CircleDot" },
      { palavra: "Boneca", icone: "Baby" },
      { palavra: "Sapo", icone: "Rabbit" },
      { palavra: "Sino", icone: "Bell" },
      { palavra: "Casa", icone: "House" },
      { palavra: "Cavalo", icone: "PawPrint" },
    ],
  },
  {
    slug: "qual-termina-igual",
    numero: 64,
    titulo: "Qual Termina Igual?",
    categoriaSlug: "consciencia-fonologica",
    objetivo: "Trabalhar a identificação do som final das palavras.",
    materiais: ["Cartões de figuras com sons finais variados"],
    comoPreparar: ["Imprima os cartões.", "Agrupe palavras com o mesmo som final."],
    comoAplicar: [
      "Fale uma palavra, por exemplo 'mão'.",
      "Pergunte qual figura termina com o mesmo som.",
      "A criança escolhe e nomeia.",
      "Repitam o som final juntos.",
    ],
    variacao: "Combine com som inicial para crianças mais avançadas.",
    cartoes: [
      { palavra: "Pão", icone: "Cookie" },
      { palavra: "Mão", icone: "Hand" },
      { palavra: "Coração", icone: "Heart" },
      { palavra: "Flor", icone: "Flower2" },
      { palavra: "Cor", icone: "Palette" },
      { palavra: "Amor", icone: "Heart" },
    ],
  },
  {
    slug: "tira-a-silaba",
    numero: 65,
    titulo: "Tira a Sílaba",
    categoriaSlug: "consciencia-fonologica",
    objetivo: "Trabalhar a manipulação silábica, descobrindo a palavra sem a primeira sílaba.",
    materiais: ["Cartões de palavras", "Figuras de apoio"],
    comoPreparar: ["Imprima os cartões.", "Escolha palavras fáceis de segmentar."],
    comoAplicar: [
      "Fale 'sapato' e peça para tirar o 'sa'.",
      "A criança descobre o que sobra: 'pato'.",
      "Use a figura para confirmar a nova palavra.",
      "Repita com outras palavras.",
    ],
    variacao: "Tire a última sílaba em vez da primeira.",
    cartoes: [
      { palavra: "Sapato", icone: "Footprints" },
      { palavra: "Boato", icone: "Volume2" },
      { palavra: "Caneta", icone: "Pen" },
      { palavra: "Bigode", icone: "Smile" },
      { palavra: "Pateta", icone: "Smile" },
      { palavra: "Macaco", icone: "PawPrint" },
    ],
  },
  {
    slug: "troca-a-silaba",
    numero: 66,
    titulo: "Troca a Sílaba",
    categoriaSlug: "consciencia-fonologica",
    objetivo: "Trabalhar a manipulação fonológica criando palavras novas ao trocar sílabas.",
    materiais: ["Cartões de sílabas", "Figuras de apoio"],
    comoPreparar: ["Imprima os cartões de sílabas.", "Tenha figuras das palavras possíveis."],
    comoAplicar: [
      "Fale 'mala' e troque 'ma' por 'sa'.",
      "A criança descobre a nova palavra: 'sala'.",
      "Use figuras para mostrar a diferença.",
      "Brinquem trocando sílabas de várias palavras.",
    ],
    variacao: "Troque a sílaba do meio em palavras maiores.",
  },
  {
    slug: "caca-rimas",
    numero: 67,
    titulo: "Caça Rimas",
    categoriaSlug: "consciencia-fonologica",
    objetivo: "Aprofundar a percepção de rimas em um jogo de busca de pares.",
    materiais: ["Cartões de figuras que rimam", "Bandeja para os pares"],
    comoPreparar: ["Imprima os cartões que rimam.", "Embaralhe e espalhe na mesa."],
    comoAplicar: [
      "A criança escolhe um cartão e fala a palavra.",
      "Ela procura outra figura que rime.",
      "Confirmem falando as duas palavras juntas.",
      "Continuem até formar todos os pares.",
    ],
    variacao: "Peça para a criança inventar uma rima nova para cada figura.",
    cartoes: [
      { palavra: "Gato", icone: "Cat" },
      { palavra: "Pato", icone: "Bird" },
      { palavra: "Bola", icone: "CircleDot" },
      { palavra: "Sacola", icone: "ShoppingBag" },
      { palavra: "Flor", icone: "Flower2" },
      { palavra: "Cor", icone: "Palette" },
    ],
  },
  {
    slug: "palavra-grande-palavra-pequena",
    numero: 68,
    titulo: "Palavra Grande, Palavra Pequena",
    categoriaSlug: "consciencia-fonologica",
    objetivo: "Comparar o tamanho sonoro das palavras pela quantidade de sílabas.",
    materiais: ["Cartões de figuras de palavras curtas e longas"],
    comoPreparar: ["Imprima os cartões.", "Misture palavras de uma e de muitas sílabas."],
    comoAplicar: [
      "Mostre duas figuras, por exemplo 'sol' e 'borboleta'.",
      "Batam palmas para contar as sílabas de cada uma.",
      "A criança diz qual palavra é maior no som.",
      "Ordene várias figuras da menor à maior.",
    ],
    variacao: "Surpreenda mostrando que objetos pequenos podem ter palavras grandes.",
    cartoes: [
      { palavra: "Sol", icone: "Sun" },
      { palavra: "Borboleta", icone: "Bug" },
      { palavra: "Pé", icone: "Footprints" },
      { palavra: "Geladeira", icone: "Refrigerator" },
      { palavra: "Mão", icone: "Hand" },
      { palavra: "Computador", icone: "Laptop" },
    ],
  },
  {
    slug: "quantos-sons",
    numero: 69,
    titulo: "Quantos Sons?",
    categoriaSlug: "consciencia-fonologica",
    objetivo: "Iniciar a consciência fonêmica contando os sons de palavras curtas.",
    materiais: ["Cartões de palavras curtas", "Fichas para marcar sons"],
    comoPreparar: ["Selecione palavras de dois e três sons.", "Separe as fichas."],
    comoAplicar: [
      "Fale uma palavra curta bem devagar: s-o-l.",
      "A criança repete alongando cada som.",
      "Ela coloca uma ficha para cada som ouvido.",
      "Conte os sons juntos.",
    ],
    variacao: "Comece com palavras de dois sons e avance aos poucos.",
  },
  {
    slug: "primeiro-som-da-palavra",
    numero: 70,
    titulo: "Primeiro Som da Palavra",
    categoriaSlug: "consciencia-fonologica",
    objetivo: "Isolar o primeiro fonema das palavras, base para a leitura.",
    materiais: ["Cartões de figuras", "Cartelas de letras"],
    comoPreparar: ["Imprima as figuras e as letras.", "Deixe as letras visíveis."],
    comoAplicar: [
      "Mostre uma figura e fale a palavra.",
      "Pergunte qual é o primeiro som.",
      "A criança associa à letra correspondente.",
      "Repita com palavras de sons diferentes.",
    ],
    variacao: "Peça para a criança pensar em outra palavra com o mesmo som inicial.",
    cartoes: [
      { palavra: "Abelha", icone: "Bug" },
      { palavra: "Elefante", icone: "PawPrint" },
      { palavra: "Igreja", icone: "Church" },
      { palavra: "Ovo", icone: "Egg" },
      { palavra: "Uva", icone: "Grape" },
      { palavra: "Bola", icone: "CircleDot" },
    ],
  },
  {
    slug: "ultimo-som-da-palavra",
    numero: 71,
    titulo: "Último Som da Palavra",
    categoriaSlug: "consciencia-fonologica",
    objetivo: "Isolar o último fonema das palavras, ampliando a consciência fonêmica.",
    materiais: ["Cartões de figuras", "Cartelas de letras"],
    comoPreparar: ["Imprima figuras e letras.", "Organize as letras-alvo."],
    comoAplicar: [
      "Mostre uma figura e fale a palavra alongando o final.",
      "Pergunte qual é o último som.",
      "A criança associa à letra correspondente.",
      "Repita com palavras variadas.",
    ],
    variacao: "Junte primeiro e último som no mesmo jogo.",
  },
  {
    slug: "forme-uma-palavra-nova",
    numero: 72,
    titulo: "Forme uma Palavra Nova",
    categoriaSlug: "consciencia-fonologica",
    objetivo: "Trabalhar a manipulação fonológica criando palavras a partir de sons dados.",
    materiais: ["Cartões de letras ou sílabas", "Figuras de apoio"],
    comoPreparar: ["Imprima os cartões de letras e sílabas.", "Tenha figuras das palavras possíveis."],
    comoAplicar: [
      "Ofereça algumas sílabas, por exemplo 'pa', 'to', 'lu'.",
      "A criança combina e forma palavras possíveis.",
      "Vocês conferem se a palavra existe.",
      "Comemorem cada palavra nova formada.",
    ],
    variacao: "Use letras móveis para crianças em fase de alfabetização.",
  },
  {
    slug: "bate-palmas-das-silabas",
    numero: 73,
    titulo: "Bate-Palmas das Sílabas",
    categoriaSlug: "consciencia-fonologica",
    objetivo: "Marcar o ritmo das sílabas com o corpo, fortalecendo a consciência silábica.",
    materiais: ["Cartões de figuras", "Espaço para se mover"],
    comoPreparar: ["Imprima os cartões.", "Combine os gestos para cada sílaba."],
    comoAplicar: [
      "Mostre uma figura e nomeie a palavra.",
      "Batam palmas uma vez para cada sílaba.",
      "Troquem palmas por pulos ou batidas no pé.",
      "Contem as sílabas ao final.",
    ],
    variacao: "Faça uma música batendo as sílabas dos nomes da família.",
  },
  {
    slug: "detetive-dos-sons",
    numero: 74,
    titulo: "Detetive dos Sons",
    categoriaSlug: "consciencia-fonologica",
    objetivo: "Procurar, no ambiente, objetos cujo nome tenha um som específico.",
    materiais: ["Uma lupa de brinquedo (opcional)", "Lista do som-alvo"],
    comoPreparar: ["Defina o som a ser investigado.", "Prepare a lupa para deixar lúdico."],
    comoAplicar: [
      "Diga o som-alvo, por exemplo o som do P.",
      "A criança procura objetos com esse som na sala.",
      "Ela nomeia cada objeto encontrado.",
      "Conte quantos objetos o detetive achou.",
    ],
    variacao: "Troque o som-alvo a cada rodada.",
  },
  {
    slug: "repita-a-sequencia",
    numero: 75,
    titulo: "Repita a Sequência",
    categoriaSlug: "atencao-memoria",
    objetivo: "Ampliar a memória auditiva de curto prazo repetindo sequências crescentes.",
    materiais: ["Lista de sequências de palavras", "Ambiente tranquilo"],
    comoPreparar: ["Prepare sequências de duas a cinco palavras.", "Garanta um ambiente sem ruídos."],
    comoAplicar: [
      "Fale duas palavras e peça para a criança repetir.",
      "Acrescente uma palavra a cada acerto.",
      "Pare quando ela atingir o limite e comemore.",
      "Tente bater o recorde na próxima rodada.",
    ],
    variacao: "Use números em vez de palavras para variar.",
  },
  {
    slug: "o-que-mudou",
    numero: 76,
    titulo: "O que Mudou?",
    categoriaSlug: "atencao-memoria",
    objetivo: "Trabalhar a atenção visual e a memória observando mudanças nos objetos.",
    materiais: ["Cartões de figuras", "Um pano para cobrir"],
    comoPreparar: ["Disponha alguns cartões em fila.", "Tenha o pano para cobrir a mesa."],
    comoAplicar: [
      "A criança observa os cartões por alguns segundos.",
      "Cubra e troque ou retire um cartão.",
      "Pergunte: 'O que mudou?'.",
      "Comece com poucos cartões e aumente aos poucos.",
    ],
    variacao: "Inverta a ordem dos cartões em vez de retirar.",
  },
  {
    slug: "jogo-do-silencio",
    numero: 77,
    titulo: "Jogo do Silêncio",
    categoriaSlug: "atencao-memoria",
    objetivo: "Desenvolver a escuta seletiva e a atenção a sons do ambiente.",
    materiais: ["Ambiente comum", "Lista de sons para identificar"],
    comoPreparar: ["Escolha um momento calmo.", "Pense em sons que podem surgir."],
    comoAplicar: [
      "Peça silêncio total por alguns segundos.",
      "A criança escuta com atenção os sons ao redor.",
      "Depois, ela conta quais sons ouviu.",
      "Conversem sobre cada som identificado.",
    ],
    variacao: "Faça sons propositais para a criança identificar de olhos fechados.",
  },
  {
    slug: "qual-som-e-esse",
    numero: 78,
    titulo: "Qual Som é Esse?",
    categoriaSlug: "atencao-memoria",
    objetivo: "Trabalhar a discriminação auditiva de sons do cotidiano.",
    materiais: ["Objetos que produzem sons", "Cartões de figuras dos objetos"],
    comoPreparar: ["Reúna objetos sonoros (chaves, papel, sino).", "Imprima as figuras correspondentes."],
    comoAplicar: [
      "Produza um som sem a criança ver o objeto.",
      "Ela tenta adivinhar qual objeto fez o som.",
      "Confirme mostrando o objeto e a figura.",
      "Troquem de papéis a cada rodada.",
    ],
    variacao: "Use sons de animais ou de instrumentos musicais.",
    cartoes: [
      { palavra: "Chaves", icone: "Key" },
      { palavra: "Sino", icone: "Bell" },
      { palavra: "Papel", icone: "FileText" },
      { palavra: "Palmas", icone: "Hand" },
      { palavra: "Água", icone: "Droplet" },
      { palavra: "Tambor", icone: "Drum" },
    ],
  },
  {
    slug: "caminho-das-instrucoes",
    numero: 79,
    titulo: "Caminho das Instruções",
    categoriaSlug: "atencao-memoria",
    objetivo: "Trabalhar a memória de instruções em sequência e a atenção sustentada.",
    materiais: ["Espaço livre", "Pequenos objetos ou marcas no chão"],
    comoPreparar: ["Defina pontos no ambiente.", "Pense em comandos de movimento."],
    comoAplicar: [
      "Dê uma instrução: 'Ande até a porta e volte'.",
      "Aumente para dois e três passos.",
      "A criança executa na ordem certa.",
      "Peça para ela repetir o caminho em voz alta.",
    ],
    variacao: "A criança cria o caminho e você executa.",
  },
  {
    slug: "lembra-da-lista",
    numero: 80,
    titulo: "Lembra da Lista?",
    categoriaSlug: "atencao-memoria",
    objetivo: "Trabalhar a memória de listas, como em uma ida ao mercado.",
    materiais: ["Cartões de itens (compras)", "Sacola ou cesta de papel"],
    comoPreparar: ["Imprima os cartões de itens.", "Separe a sacola."],
    comoAplicar: [
      "Diga: 'Vou ao mercado e vou comprar maçã e pão'.",
      "A criança repete a lista.",
      "Acrescentem um item por vez, sempre repetindo tudo.",
      "Vejam até onde a memória aguenta.",
    ],
    variacao: "Use os cartões como apoio para crianças mais novas.",
    cartoes: [
      { palavra: "Maçã", icone: "Apple" },
      { palavra: "Pão", icone: "Cookie" },
      { palavra: "Leite", icone: "Milk" },
      { palavra: "Ovo", icone: "Egg" },
      { palavra: "Banana", icone: "Banana" },
      { palavra: "Queijo", icone: "Sandwich" },
    ],
  },
  {
    slug: "faca-na-ordem",
    numero: 81,
    titulo: "Faça na Ordem",
    categoriaSlug: "atencao-memoria",
    objetivo: "Trabalhar a memória de trabalho executando ações na sequência pedida.",
    materiais: ["Cartões de ações simples"],
    comoPreparar: ["Imprima os cartões de ações.", "Combine um espaço para se mover."],
    comoAplicar: [
      "Dê uma sequência: 'Pule, gire e sente'.",
      "A criança executa na ordem exata.",
      "Aumente o número de ações aos poucos.",
      "Peça para ela repetir a ordem antes de fazer.",
    ],
    variacao: "Inverta a ordem: peça para fazer de trás para frente.",
    cartoes: [
      { palavra: "Pular", icone: "Rabbit" },
      { palavra: "Girar", icone: "RefreshCw" },
      { palavra: "Sentar", icone: "Armchair" },
      { palavra: "Bater palmas", icone: "Hand" },
      { palavra: "Agachar", icone: "ArrowDown" },
      { palavra: "Acenar", icone: "Hand" },
    ],
  },
  {
    slug: "sim-ou-nao",
    numero: 82,
    titulo: "Sim ou Não",
    categoriaSlug: "atencao-memoria",
    objetivo: "Trabalhar a atenção a detalhes e a compreensão de frases.",
    materiais: ["Cartões de afirmações", "Placas de sim e não"],
    comoPreparar: ["Imprima os cartões e as placas.", "Entregue as placas para a criança."],
    comoAplicar: [
      "Leia uma afirmação: 'O céu é verde'.",
      "A criança levanta a placa de sim ou não.",
      "Peça para ela corrigir o que está errado.",
      "Aumente o ritmo das afirmações.",
    ],
    variacao: "Misture afirmações fáceis e pegadinhas para manter a atenção.",
  },
  {
    slug: "eco-das-palavras",
    numero: 83,
    titulo: "Eco das Palavras",
    categoriaSlug: "atencao-memoria",
    objetivo: "Treinar a memória imediata repetindo grupos de palavras como um eco.",
    materiais: ["Lista de grupos de palavras", "Ambiente tranquilo"],
    comoPreparar: ["Monte grupos de duas a quatro palavras.", "Escolha um local sem distrações."],
    comoAplicar: [
      "Fale um grupo de palavras como se fosse um eco.",
      "A criança repete na mesma ordem.",
      "Brinque com eco forte e eco fraco.",
      "Aumente os grupos gradualmente.",
    ],
    variacao: "Peça para repetir só a primeira e a última palavra.",
  },
  {
    slug: "achou-o-par",
    numero: 84,
    titulo: "Achou o Par",
    categoriaSlug: "atencao-memoria",
    objetivo: "Trabalhar a memória visual no clássico jogo de pares.",
    materiais: ["Dois conjuntos iguais de cartões de figuras"],
    comoPreparar: ["Imprima dois conjuntos iguais.", "Embaralhe e vire todos para baixo."],
    comoAplicar: [
      "A criança vira dois cartões por vez.",
      "Ela nomeia cada figura ao virar.",
      "Se formarem par, ela guarda; se não, vira de novo.",
      "Vence quem juntar mais pares.",
    ],
    variacao: "Comece com poucos pares e aumente conforme a memória melhora.",
  },
  {
    slug: "ouca-e-desenhe",
    numero: 85,
    titulo: "Ouça e Desenhe",
    categoriaSlug: "atencao-memoria",
    objetivo: "Unir escuta atenta e compreensão seguindo instruções para desenhar.",
    materiais: ["Folha de papel", "Lápis de cor"],
    comoPreparar: ["Separe papel e lápis.", "Pense em instruções simples de desenho."],
    comoAplicar: [
      "Dê instruções: 'Desenhe um sol no canto de cima'.",
      "A criança escuta e desenha o que foi pedido.",
      "Acrescente detalhes um a um.",
      "Comparem o desenho com as instruções dadas.",
    ],
    variacao: "Inverta: a criança dá as instruções e você desenha.",
  },
  {
    slug: "conte-os-sons",
    numero: 86,
    titulo: "Conte os Sons",
    categoriaSlug: "atencao-memoria",
    objetivo: "Trabalhar a atenção auditiva contando quantas vezes um som aconteceu.",
    materiais: ["Um instrumento ou objeto sonoro", "Fichas para contar"],
    comoPreparar: ["Escolha um som claro, como batidas.", "Separe as fichas de contagem."],
    comoAplicar: [
      "Faça o som algumas vezes, sem a criança ver.",
      "Ela conta quantas vezes ouviu.",
      "Coloque uma ficha para cada som.",
      "Confiram juntos o total.",
    ],
    variacao: "Varie o ritmo dos sons, com pausas, para aumentar o desafio.",
  },
  {
    slug: "quem-falou",
    numero: 87,
    titulo: "Quem Falou?",
    categoriaSlug: "atencao-memoria",
    objetivo: "Trabalhar a discriminação auditiva de vozes e a atenção.",
    materiais: ["Algumas pessoas ou gravações de vozes", "Venda para os olhos (opcional)"],
    comoPreparar: ["Reúna duas ou mais vozes conhecidas.", "Prepare a venda se quiser."],
    comoAplicar: [
      "A criança fecha os olhos ou usa a venda.",
      "Uma pessoa fala uma frase curta.",
      "A criança adivinha quem falou.",
      "Variem as vozes e o tom para desafiar.",
    ],
    variacao: "Use sons de animais imitados por cada participante.",
  },
  {
    slug: "comeco-meio-e-fim",
    numero: 88,
    titulo: "Começo, Meio e Fim",
    categoriaSlug: "sequencia-narrativa",
    objetivo: "Trabalhar a estrutura narrativa identificando as três partes de uma história.",
    materiais: ["Cartões de cenas em três etapas", "Tapete dividido em três partes"],
    comoPreparar: ["Imprima os cartões de cenas.", "Marque três espaços: começo, meio e fim."],
    comoAplicar: [
      "Entregue três cartões de uma história.",
      "A criança coloca cada um no espaço certo.",
      "Ela conta o que acontece em cada parte.",
      "Pergunte o que ligou uma parte à outra.",
    ],
    variacao: "Misture cartões de duas histórias para ela separar.",
    cartoes: [
      { palavra: "Começo", icone: "Play" },
      { palavra: "Meio", icone: "CircleDot" },
      { palavra: "Fim", icone: "Flag" },
    ],
  },
  {
    slug: "antes-e-depois",
    numero: 89,
    titulo: "Antes e Depois",
    categoriaSlug: "sequencia-narrativa",
    objetivo: "Trabalhar a noção temporal relacionando o que vem antes e depois de uma cena.",
    materiais: ["Cartões de cenas com etapas", "Cartões de 'antes' e 'depois'"],
    comoPreparar: ["Imprima os cartões.", "Separe os marcadores de antes e depois."],
    comoAplicar: [
      "Mostre uma cena central, por exemplo 'comer o bolo'.",
      "Pergunte o que aconteceu antes e o que vem depois.",
      "A criança escolhe ou descreve as cenas.",
      "Montem a sequência completa juntos.",
    ],
    variacao: "Use fotos de momentos reais do dia da criança.",
  },
  {
    slug: "ordene-a-receita",
    numero: 90,
    titulo: "Ordene a Receita",
    categoriaSlug: "sequencia-narrativa",
    objetivo: "Trabalhar a sequência lógica de passos seguindo uma receita simples.",
    materiais: ["Cartões dos passos de uma receita (ex.: vitamina)"],
    comoPreparar: ["Imprima os cartões dos passos.", "Embaralhe a ordem."],
    comoAplicar: [
      "Apresente os passos embaralhados.",
      "A criança coloca na ordem certa de fazer.",
      "Ela explica cada passo em voz alta.",
      "Conversem sobre o que aconteceria se trocasse a ordem.",
    ],
    variacao: "Façam a receita de verdade seguindo a sequência montada.",
    cartoes: [
      { palavra: "Pegar a fruta", icone: "Banana" },
      { palavra: "Cortar", icone: "Scissors" },
      { palavra: "Bater", icone: "RefreshCw" },
      { palavra: "Servir", icone: "CupSoda" },
    ],
  },
  {
    slug: "monte-a-rotina-da-manha",
    numero: 91,
    titulo: "Monte a Rotina da Manhã",
    categoriaSlug: "sequencia-narrativa",
    objetivo: "Organizar em sequência as etapas da rotina matinal.",
    materiais: ["Cartões da rotina da manhã", "Trilho de papel"],
    comoPreparar: ["Imprima os cartões da rotina.", "Desenhe um trilho para ordenar."],
    comoAplicar: [
      "Espalhe os cartões da manhã embaralhados.",
      "A criança organiza do acordar ao sair de casa.",
      "Ela narra a rotina em ordem.",
      "Pergunte o que ela faz primeiro e por último.",
    ],
    variacao: "Monte também a rotina da noite.",
    cartoes: [
      { palavra: "Acordar", icone: "Sun" },
      { palavra: "Escovar dentes", icone: "Sparkles" },
      { palavra: "Tomar café", icone: "Coffee" },
      { palavra: "Vestir roupa", icone: "Shirt" },
      { palavra: "Calçar sapato", icone: "Footprints" },
      { palavra: "Ir à escola", icone: "Backpack" },
    ],
  },
  {
    slug: "o-que-aconteceu-primeiro",
    numero: 92,
    titulo: "O que Aconteceu Primeiro?",
    categoriaSlug: "sequencia-narrativa",
    objetivo: "Trabalhar a ordenação temporal entre dois eventos relacionados.",
    materiais: ["Pares de cartões de eventos (causa e tempo)"],
    comoPreparar: ["Imprima os pares de eventos.", "Embaralhe os cartões."],
    comoAplicar: [
      "Mostre dois cartões, por exemplo 'plantar' e 'flor crescida'.",
      "Pergunte: 'O que aconteceu primeiro?'.",
      "A criança ordena e justifica.",
      "Repita com outros pares.",
    ],
    variacao: "Use três eventos para crianças mais avançadas.",
  },
  {
    slug: "continue-a-historia",
    numero: 93,
    titulo: "Continue a História",
    categoriaSlug: "sequencia-narrativa",
    objetivo: "Estimular a criatividade narrativa e a coerência ao dar continuidade a uma história.",
    materiais: ["Cartões de início de história", "Figuras de apoio"],
    comoPreparar: ["Imprima os cartões de início.", "Separe figuras para inspirar."],
    comoAplicar: [
      "Leia o começo de uma história.",
      "A criança continua contando o que acontece.",
      "Faça perguntas para ampliar a narrativa.",
      "Cheguem juntos a um final.",
    ],
    variacao: "Cada um acrescenta uma frase, alternando a narração.",
  },
  {
    slug: "imagine-o-final",
    numero: 94,
    titulo: "Imagine o Final",
    categoriaSlug: "sequencia-narrativa",
    objetivo: "Trabalhar a inferência e a criatividade criando finais para histórias.",
    materiais: ["Cartões de histórias sem final", "Figuras de apoio"],
    comoPreparar: ["Imprima histórias curtas sem desfecho.", "Tenha figuras de apoio."],
    comoAplicar: [
      "Conte uma história até o clímax.",
      "Pergunte: 'Como você acha que termina?'.",
      "A criança cria o final com detalhes.",
      "Comparem diferentes finais possíveis.",
    ],
    variacao: "Peça um final feliz e um final engraçado para a mesma história.",
  },
  {
    slug: "conte-com-suas-palavras",
    numero: 95,
    titulo: "Conte com suas Palavras",
    categoriaSlug: "sequencia-narrativa",
    objetivo: "Trabalhar o reconto fiel de uma história mantendo a sequência dos fatos.",
    materiais: ["Uma história curta ilustrada", "Cartões das cenas"],
    comoPreparar: ["Escolha uma história curta.", "Separe os cartões das cenas principais."],
    comoAplicar: [
      "Conte a história mostrando as cenas.",
      "Guarde o livro e peça o reconto.",
      "A criança usa os cartões como apoio.",
      "Reforce a ordem correta dos acontecimentos.",
    ],
    variacao: "Peça o reconto sem os cartões para desafiar a memória.",
  },
  {
    slug: "sequencia-de-quatro-cenas",
    numero: 96,
    titulo: "Sequência de 4 Cenas",
    categoriaSlug: "sequencia-narrativa",
    objetivo: "Ampliar a complexidade narrativa ordenando histórias de quatro etapas.",
    materiais: ["Cartões de histórias em quatro cenas"],
    comoPreparar: ["Imprima as quatro cenas de cada história.", "Embaralhe os cartões."],
    comoAplicar: [
      "Entregue as quatro cenas embaralhadas.",
      "A criança organiza na ordem correta.",
      "Ela conta a história completa.",
      "Pergunte sobre os detalhes de cada cena.",
    ],
    variacao: "Aumente para cinco ou seis cenas conforme a evolução.",
    cartoes: [
      { palavra: "Cena 1", icone: "Play" },
      { palavra: "Cena 2", icone: "ArrowRight" },
      { palavra: "Cena 3", icone: "ArrowRight" },
      { palavra: "Cena 4", icone: "Flag" },
    ],
  },
  {
    slug: "problema-e-solucao",
    numero: 97,
    titulo: "Problema e Solução",
    categoriaSlug: "sequencia-narrativa",
    objetivo: "Trabalhar o raciocínio narrativo relacionando um problema à sua solução.",
    materiais: ["Cartões de problemas", "Cartões de soluções"],
    comoPreparar: ["Imprima os dois grupos de cartões.", "Embaralhe cada grupo."],
    comoAplicar: [
      "Mostre um problema: 'O brinquedo quebrou'.",
      "A criança procura uma solução possível.",
      "Ela explica como a solução resolve o problema.",
      "Pensem juntos em outras soluções.",
    ],
    variacao: "Peça para a criança inventar o problema e a solução.",
  },
  {
    slug: "linha-do-tempo-do-dia",
    numero: 98,
    titulo: "Linha do Tempo do Dia",
    categoriaSlug: "sequencia-narrativa",
    objetivo: "Organizar os principais momentos do dia em uma linha do tempo.",
    materiais: ["Cartões de momentos do dia", "Fita ou barbante para a linha"],
    comoPreparar: ["Imprima os cartões dos momentos.", "Estenda a linha do tempo na mesa."],
    comoAplicar: [
      "A criança posiciona os momentos na linha.",
      "Ela narra o dia do início ao fim.",
      "Pergunte o que vem entre dois momentos.",
      "Conversem sobre a duração de cada parte do dia.",
    ],
    variacao: "Inclua momentos especiais, como uma festa, na sequência.",
    cartoes: [
      { palavra: "Manhã", icone: "Sunrise" },
      { palavra: "Tarde", icone: "Sun" },
      { palavra: "Noite", icone: "Moon" },
      { palavra: "Dormir", icone: "Bed" },
    ],
  },
  {
    slug: "personagem-lugar-e-acao",
    numero: 99,
    titulo: "Personagem, Lugar e Ação",
    categoriaSlug: "sequencia-narrativa",
    objetivo: "Construir histórias combinando os três elementos básicos da narrativa.",
    materiais: ["Cartões de personagens", "Cartões de lugares", "Cartões de ações"],
    comoPreparar: ["Imprima os três grupos de cartões.", "Separe um monte de cada tipo."],
    comoAplicar: [
      "A criança sorteia um cartão de cada grupo.",
      "Ela cria uma história unindo os três.",
      "Faça perguntas para enriquecer a narrativa.",
      "Repita com novas combinações.",
    ],
    variacao: "Acrescente um cartão de 'problema' para complicar a história.",
    cartoes: [
      { palavra: "Menina", icone: "User" },
      { palavra: "Cachorro", icone: "Dog" },
      { palavra: "Parque", icone: "Trees" },
      { palavra: "Praia", icone: "Waves" },
      { palavra: "Correr", icone: "Footprints" },
      { palavra: "Brincar", icone: "ToyBrick" },
    ],
  },
  {
    slug: "crie-sua-propria-historia",
    numero: 100,
    titulo: "Crie sua Própria História",
    categoriaSlug: "sequencia-narrativa",
    objetivo: "Integrar todas as habilidades narrativas criando uma história completa e original.",
    materiais: ["Cartões variados de personagens, lugares e objetos", "Folha para registrar"],
    comoPreparar: ["Reúna cartões de vários tipos.", "Separe uma folha para anotar a história."],
    comoAplicar: [
      "A criança escolhe os cartões que quiser.",
      "Ela cria uma história com começo, meio e fim.",
      "Estimule detalhes sobre personagens e lugar.",
      "Registrem a história para ela contar de novo depois.",
    ],
    variacao: "Transforme a história em um pequeno teatro com os cartões.",
  },
]

export function getAtividade(slug: string) {
  return atividades.find((a) => a.slug === slug)
}

export function getCategoria(slug: string) {
  return categorias.find((c) => c.slug === slug)
}

export function atividadesPorCategoria(categoriaSlug: string) {
  return atividades.filter((a) => a.categoriaSlug === categoriaSlug)
}
